"""Generate Slack incident update drafts from investigation output."""

from __future__ import annotations

import uuid

from app.models import Hypothesis, Incident, SlackDraft, TimelineEvent
from app.services.vector_search.similarity_service import SimilarityContext


class SlackDraftGenerator:
    def generate(
        self,
        *,
        organization_id: uuid.UUID,
        incident: Incident,
        investigation_run_id: uuid.UUID,
        timeline_events: list[TimelineEvent],
        hypothesis: Hypothesis | None,
        similarity: SimilarityContext | None = None,
    ) -> SlackDraft:
        lines = [
            f"*Incident:* {incident.title}",
            f"*Status:* {incident.status}",
        ]
        if hypothesis:
            lines.append(f"*Working theory:* {hypothesis.title}")
            if hypothesis.description:
                lines.append(hypothesis.description)

        if timeline_events:
            lines.append("*Timeline (latest first):*")
            for event in reversed(timeline_events[:5]):
                ts = event.event_time.isoformat() if event.event_time else "unknown"
                lines.append(f"• [{ts}] {event.title}")

        if similarity is not None and similarity.total() > 0:
            lines.append("*From organizational memory:*")
            for match in similarity.similar_incidents[:3]:
                label = match.title or "past incident"
                lines.append(f"• Similar incident: {label} (score {match.score})")
            for match in similarity.relevant_runbooks[:3]:
                label = match.title or "runbook"
                lines.append(f"• Runbook: {label} (score {match.score})")
            for match in similarity.related_postmortems[:2]:
                label = match.title or "postmortem"
                lines.append(f"• Postmortem: {label} (score {match.score})")

        lines.append("_Draft generated by Breadcrumbs investigation engine (MVP)._")

        return SlackDraft(
            organization_id=organization_id,
            incident_id=incident.id,
            investigation_run_id=investigation_run_id,
            channel="#incidents",
            content="\n".join(lines),
            status="draft",
        )
