"""Generate Slack incident update drafts from investigation output."""

from __future__ import annotations

import uuid

from app.models import Hypothesis, Incident, SlackDraft, TimelineEvent


class SlackDraftGenerator:
    def generate(
        self,
        *,
        organization_id: uuid.UUID,
        incident: Incident,
        investigation_run_id: uuid.UUID,
        timeline_events: list[TimelineEvent],
        hypothesis: Hypothesis | None,
    ) -> SlackDraft:
        lines = [
            f"*Incident:* {incident.title}",
            f"*Status:* {incident.status}",
        ]
        if hypothesis:
            lines.append(f"*Working theory:* {hypothesis.title}")
            if hypothesis.description:
                lines.append(hypothesis.description)

        if timeline_events:
            lines.append("*Timeline (latest first):*")
            for event in reversed(timeline_events[:5]):
                ts = event.event_time.isoformat() if event.event_time else "unknown"
                lines.append(f"• [{ts}] {event.title}")

        lines.append("_Draft generated by Breadcrumbs investigation engine (MVP)._")

        return SlackDraft(
            organization_id=organization_id,
            incident_id=incident.id,
            investigation_run_id=investigation_run_id,
            channel="#incidents",
            content="\n".join(lines),
            status="draft",
        )
